name: nbnl-env

services:
  nbnl-env:
    image: nbnl-env
    volumes:
      - .:/project
    working_dir: /project
    user: "${USER_ID}:${GROUP_ID}"
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - RUNNING_IN_DOCKER=true
      - GIT_USER_NAME="Bart Kleijngeld"
      - GIT_USER_EMAIL="bartkl@gmail.com"
    entrypoint: /project/entrypoint.sh
    command: bash
